"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignInButton, SignOutButton,SignIn,Show,UserButton,SignUp} from "@clerk/nextjs";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Show when="signed-out">
            <div className="flex items-center justify-center h-screen">
              <SignIn />
              <SignUp />

            </div>
          </Show>

          <Show when="signed-in">
            {children}
            
          </Show>
        </body>
      </html>
    </ClerkProvider>
  );
}